Readme
andnil5/dd2480-grp12-assignment2 pull request #36
Opened 2021-02-16 11:54 UTC by jenniferlindberg

Final README.

2021-02-16 14:48 UTC, majate requested changes
I like the over all structure! :smiley: Please look at my more specific comments and suggestions.

2021-02-16 14:48 UTC, majate commented on README.md
> +- Linting the whole project `flake8 path/to/project_folder/`
Might be good to mention that the CI server runs flake8 with the option `--ignore=E501` to ignore any "Line too long" errors from lines with more than 79 characters.

2021-02-16 14:48 UTC, majate commented on README.md
> +This command generates an ngrok "URL" that should be added to `BASE_URL` variable inside the `status_response` file.
Might be good to mention that this url must be connected to a webhook for push events in the targeted repo.

2021-02-16 14:48 UTC, majate commented on README.md
> +Further documentation can be found in the `api.md` file in the `docs` folder. Moreover, further code documentation can be found [here](https://majate.github.io/testing/src/index.html).
The content at this link will not be updated when the docs directory in this repo is updated, a better link is: https://andnil5.github.io/dd2480-grp12-assignment2/src/

2021-02-16 14:48 UTC, majate commented on README.md
> +The branch that has been changed is compiled by the CI server. The compilation is triggered as webhook. Furthermore, a static syntax check is performed.
With this formulation, it sounds a bit as if the CI server compile the code and run a static syntax check as two different things. However, we only use a linter tool (flake8) to run a static syntax check. In fact, we don't really compile the code at all. Maybe a more descriptive formulation would be something along the lines of:

*Whenever the GitHub webhook register a push event to the CI server, the repo state of the head commit of the push will be analysed by the CI server. The “compilation” part of the CI workflows consists of the CI server performing a static syntax check of the pushed code by using the linter tool flake8. The code passes this step if flake8 finds no errors (ignoring warnings and the E501 error).*

2021-02-16 14:48 UTC, majate commented on README.md
> +The CI server executes automated tests on the branch that has been changed. The testing is triggerd as webhook.
Might be good to mention that the tests that are executed are all the tests that are included in the target repo (and follow the naming convention of pytest tests). It might also be good to say “by a webhook” instead of “as webhook”, since the involved webhook is the mechanism provided by GitHub that makes a POST request to our server whenever a push event occurs.

2021-02-16 14:48 UTC, majate commented on README.md
> +Whenever something is pushed to a particular branch [feature 1 and feature 2](#Features-of-CI), compilation and testing, are conducted. Compilation uses the linter [flake8](https://flake8.pycqa.org/e
Only a few tests are written with mock-ups so it might be better to just say "tests are constructed using pytest" or to mention that some tests are conducted using mock-ups.

2021-02-16 14:48 UTC, majate commented on README.md
> +2. Make a change to a file in the repository
The step "2. Run `python src/server.py` from the root directory to start the server" should be added after "1. Run ngrok"

2021-02-16 14:54 UTC, jenniferlindberg commented on README.md
> +The CI server uses the notification mechanism of setting a [commit status](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks) on the repository, using
That is a good point, I will change it!

2021-02-16 14:59 UTC, jenniferlindberg commented on README.md
> +- `export PYTHONPATH=src`
Good catch!

2021-02-16 15:04 UTC, jenniferlindberg commented on README.md
> +Further documentation can be found in the `api.md` file in the `docs` folder. Moreover, further code documentation can be found [here](https://majate.github.io/testing/src/index.html).
Perfect!

2021-02-16 15:12 UTC, jenniferlindberg commented on README.md
> +Whenever something is pushed to a particular branch [feature 1 and feature 2](#Features-of-CI), compilation and testing, are conducted. Compilation uses the linter [flake8](https://flake8.pycqa.org/e
Good point!

2021-02-16 15:16 UTC, jenniferlindberg commented
I have now updated Maja's points above.

2021-02-16 15:39 UTC, CalleFreme commented on README.md
> +Implementation of a small continuous integration CI server containing core features of continuous integration.
Continuous Integration = CI so maybe phrase it with parantheses, like:
"Implementation of a small continuous integration (CI) server..."

2021-02-16 15:40 UTC, CalleFreme commented on README.md
> +The core CI features of continous integration are the following:
Again, somewhat redudant phrasing. Maybe try out something like:
"The core features of CI are as follows:"

2021-02-16 15:43 UTC, CalleFreme requested changes
A couple of phrasing suggestions for the introductory part of README :)

2021-02-16 16:27 UTC, andnil5 requested changes

2021-02-16 16:27 UTC, andnil5 commented on README.md
> +2. Run `python src/server.py` from the root directory to start the server
We should clarify that the user MUST be in the root directory (and not src) when running server.py since it won't work from the src dir atm. A small note after this sentence?

2021-02-16 16:45 UTC, majate approved these changes

2021-02-17 07:49 UTC, andnil5 commented
Nice overall structure! 👍 See my comment above. Also, we should state that the user needs to configure an env.py file in the root directory. The CI env.py file must contain a personal git token and a BASE_URL where the server runs. This is necessary for the CI server to work properly.
BASE_URL = {BASE_URL}, string
TOKEN = {TOKEN}, string

2021-02-17 13:44 UTC, jenniferlindberg commented on README.md
> +Implementation of a small continuous integration CI server containing core features of continuous integration.
Hmm that is true, it was stated like that in the task description but it sounds reasonable to add a parentheses! Good point!

2021-02-17 13:48 UTC, jenniferlindberg commented on README.md
> +2. Run `python src/server.py` from the root directory to start the server
Great point!

2021-02-17 13:57 UTC, jenniferlindberg commented
I have no updated according to the comments above (@andnil5 and @CalleFreme), please check if it looks okay! :raised_hands:

2021-02-17 14:26 UTC, CalleFreme approved these changes

2021-02-17 14:30 UTC, andnil5 approved these changes

2021-02-17 14:33 UTC, merged