Change response return code to 404 for requests of non existing log files.
andnil5/dd2480-grp12-assignment2 pull request #37
Opened 2021-02-16 14:58 UTC by andnil5

Resolve #32.
Moves BASE_URL to env.py

2021-02-16 15:45 UTC, CalleFreme approved these changes

2021-02-16 17:04 UTC, majate requested changes
Se my comments :)

2021-02-16 17:04 UTC, majate commented on src/server.py
> +        The content of the file. Returns a 404 response if file is not found.
`abort(404)` does not return anything, it raises an HTTPException (see the [flask documentation](https://flask.palletsprojects.com/en/1.1.x/api/#flask.abort)). Therefore it might be better to remove "Returns a 404 response if file is not found." form the Returns section and instead add an Raises section with this information.

2021-02-16 17:04 UTC, majate commented on src/server.py
>          If `name` does not correspond to the log file of a specific flake8 run.
This should be updated to 404 now.

2021-02-16 17:04 UTC, majate commented on src/server.py
>          If `name` does not correspond to the log file of a specific pytest run.
This should be updated to 404 now.

2021-02-17 14:27 UTC, jenniferlindberg commented
It looks good now! Ready to merge :smiley:

2021-02-17 14:27 UTC, jenniferlindberg approved these changes

2021-02-17 14:43 UTC, merged