Unittest
andnil5/dd2480-grp12-assignment2 pull request #39
Opened 2021-02-16 19:46 UTC by omidhzr

I have now got the tests go through, but the branch is no more usable as I changed many things along the way. so therefore this is a draft for you to checkout and give feedback

2021-02-16 23:19 UTC, CalleFreme commented on src/ci_utils.py
> +    file_path = '/src/env.py'
Does this always work? On my machine you need to provide '**..**/src/env.py'

2021-02-17 00:23 UTC, majate reviewed
I like that you have made the server clone a temporary repo instead of fetching an old one! 😃 Maybe it would also be good to make the server delete the repo when it is done?

2021-02-17 00:23 UTC, majate commented on tests/test_ci_utils.py
> +    cwd = os.getcwd().split('/')[-2:]
This does not work on windows since paths are written with backslashes. To handle all platforms, this could be rewritten as:
```
path = os.path.normpath(os.getcwd())
cwd = path.split(os.sep)[-2:]
```
Sources: [stack owerflow](https://stackoverflow.com/questions/3167154/how-to-split-a-dos-path-into-its-components-in-python) & [docs for os.path.normpath](https://docs.python.org/3/library/os.path.html#os.path.normpath)

2021-02-17 00:23 UTC, majate commented on tests/test_ci_utils.py
> +    assert cwd_stringified == 'branch_repo/git_repo'
If the unnecessary calls to change_dir are removed from the two other tests, the current working directory should be the root. Therefore, cwd_stringified will be `<root>/git_repo`. It would therefore be better to only look at the last part of the path and check that it equals 'git_repo' instead of looking at the two last parts of the path.

2021-02-17 00:28 UTC, majate commented on tests/test_ci_utils.py
> +    assert cwd_stringified == 'branch_repo/git_repo'
One could also check that the full path is ok by:
```py
path_before = os.path.normpath(os.getcwd()).split(os.sep)
dir = './git_repo'
change_dir(dir)
path_after = os.path.normpath(os.getcwd()).split(os.sep)
assert path_before + ['git_repo'] == path_after
```

2021-02-17 01:02 UTC, majate commented on src/ci_utils.py
> +    file_path = '/src/env.py'
Currently I also need to change the path on my computer in this branch. When we are happy with the placements of change_dir in this branch, we must make sure that this path is updated to match the correct location.

2021-02-17 01:06 UTC, majate commented on src/ci_utils.py
> +def clone_git_repo(branch):
After creating the repo we should call `create_env_file`.

2021-02-17 09:40 UTC, omidhzr commented on tests/test_ci_utils.py
> +    clone_git_repo(res['branch'])
or even 
clone_git_repo('test')

2021-02-17 10:25 UTC, CalleFreme commented on src/ci_utils.py
>  import sys
It will actually probably be used with the handling of python versions in subprocesses :)

2021-02-17 11:41 UTC, omidhzr commented on src/ci_utils.py
> +    gt.pull()
I used the same commands from earlier implementation, that's why..

2021-02-17 11:44 UTC, omidhzr commented on src/server.py
> +
I remove it then

2021-02-17 11:53 UTC, omidhzr commented on tests/test_ci_utils.py
> +    with the assumption that parse and change_dir function as intended"""
yes hahah

2021-02-17 12:35 UTC, omidhzr commented on src/ci_utils.py
> +import git
I think it is the same, it is just that you import it like that: [gitPython](https://gitpython.readthedocs.io/en/stable/tutorial.html)

2021-02-17 12:37 UTC, omidhzr commented on src/ci_utils.py
>  import sys
sys is used run_compile(), I tried to remove but then got error

2021-02-17 14:08 UTC, omidhzr commented on tests/test_ci_utils.py
> +    with the assumption that parse and change_dir function as intended"""
removed

2021-02-17 14:22 UTC, omidhzr commented on src/ci_utils.py
> +def clone_git_repo(branch):
done

2021-02-17 18:06 UTC, majate requested changes
Some comments regarding bad paths and flake8 errors. Implementing the changes makes the server run properly on my computer :)

2021-02-17 18:12 UTC, omidhzr commented on src/ci_utils.py
>      create_env_file()
we resolved this with Anders

2021-02-17 19:45 UTC, majate approved these changes

2021-02-17 19:58 UTC, merged